---
- name: Time Synchronization
  hosts: database_servers
  become: true

  pre_tasks: 
    - name: Display info
      debug: 
        msg: "The role going to run after this tasks"

  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: Set timezone
      timezone:
        name: "{{ host_timezone }}"
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      service:
        name: chronyd
        state: restarted

