---
- name: configure Message of the day
  hosts: all
  remote_user: ansible
  become: true
  vars:
    - system_owner: stan@example.com

  tasks:
    - name: configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
