---
- name: Install Apache and starts the service
  hosts: node4
  become: true
  gather_facts: true

  tasks:
    - name: Install the required package
      yum:
        name: "{{ ansible_facts.ansible_local.custom.general.package }}"
        state: latest
  
    - name: start and enable the service
      service:
        name: "{{ ansible_facts['ansible_local']['custom']['general']['service'] }}"
        state: "{{ ansible_facts['ansible_local']['custom']['general']['state'] }}"
        enabled: "{{ ansible_facts['ansible_local']['custom']['general']['enabled'] }}"

    - name: Add Information to /var/www/html/index.html
      copy:
        content: "{{ ansible_facts['os_family'] }}: {{ ansible_default_ipv4['address'] }}: {{ ansible_facts.distribution }}"
        dest: /var/www/html/index.html

