---
- name: Use myvhost role playbook
  hosts: webservers
  become: true

  pre_tasks:
    - name: pre_tasks message
      debug:
        msg: 'Ensure web server is configured.'

  roles:
    - myvhost

  post_tasks:
    - name: post_tasks message
      debug:
        msg: 'Web server is configured.'
