---
- name: create user accounts in all servers
  hosts: all
  gather_facts: false
  become: true
  remote_user: ansible
  vars_files: secret.yml

  tasks:
    - name: Creating user from secret.yml
      user:
        name: "{{ username }}"
        password: "{{ passhash }}"
